import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { credentialsFromEnv, queryRows, type D1Credentials } from './load-d1.ts';

/**
 * Which sources are actually worth having.
 *
 * Built from the database rather than from one fetch, because a single check
 * shows what a source returned this morning and the question is what it
 * returns over time. A feed that lands one excellent piece a week beats one
 * that lands forty near-misses a day, and only accumulated history separates
 * them.
 *
 * Four measures, because no single one is honest on its own:
 *
 *   articles     volume. Necessary, and the easiest to mistake for quality.
 *   mean AI      how central AI is to what this source contributes. A source
 *                can clear the gate constantly while sitting just above it.
 *   production   the share with evidence of something actually running. This
 *                is the closest thing to "did we learn about a real use case",
 *                and it is the measure worth optimising.
 *   use case     the share where the article describes the use case in words
 *                we can quote. Low here means a source announces things
 *                without saying what they do.
 *
 * The report is written to a file and committed, so the ranking is a record
 * that accumulates rather than a number that scrolls past in a log.
 */

interface SourceRow {
  source_id: string;
  source_name: string;
  publisher_kind: string;
  articles: number;
  mean_ai: number;
  max_ai: number;
  in_production: number;
  piloting: number;
  with_use_case: number;
  first_seen: string | null;
  last_seen: string | null;
}

interface ProcessRow { source_id: string; value: string; n: number }

const BAR_WIDTH = 12;
const bar = (fraction: number): string => {
  const filled = Math.round(Math.max(0, Math.min(1, fraction)) * BAR_WIDTH);
  return '█'.repeat(filled) + '·'.repeat(BAR_WIDTH - filled);
};

/**
 * One number to sort by.
 *
 * Production evidence is weighted highest because it is what the brief asked
 * for — banks running AI, not banks discussing it. Mean AI focus comes next.
 * Volume is deliberately dampened with a logarithm: it should break ties
 * between comparable sources, not let a firehose outrank a specialist.
 */
export function qualityScore(r: {
  articles: number; mean_ai: number; in_production: number; with_use_case: number;
}): number {
  if (r.articles === 0) return 0;
  const productionRate = r.in_production / r.articles;
  const useCaseRate = r.with_use_case / r.articles;
  return Math.round(
    productionRate * 50
    + (r.mean_ai / 100) * 30
    + useCaseRate * 20
    + Math.log10(r.articles + 1) * 4,
  );
}

export function renderReport(
  rows: SourceRow[], processes: ProcessRow[], generatedAt: string,
): string {
  const ranked = [...rows]
    .map((r) => ({ ...r, score: qualityScore(r) }))
    .sort((a, b) => b.score - a.score);

  const byProcess = new Map<string, ProcessRow[]>();
  for (const p of processes) {
    const list = byProcess.get(p.source_id) ?? [];
    list.push(p);
    byProcess.set(p.source_id, list);
  }

  const total = rows.reduce((n, r) => n + r.articles, 0);
  const out: string[] = [];

  out.push('# Which sources are worth having');
  out.push('');
  out.push(`Generated ${generatedAt} from ${total} stored articles across ${rows.length} sources.`);
  out.push('Regenerated by the **Check sources** action — do not edit by hand.');
  out.push('');
  out.push('Ranked by a score that weights **evidence of production** highest (50),');
  out.push('then **mean AI focus** (30), then **whether the use case is described** (20),');
  out.push('with volume dampened logarithmically so a firehose cannot outrank a specialist.');
  out.push('');
  out.push('| # | Source | Articles | Mean AI | In production | Use case described | Score |');
  out.push('|---|---|--:|--:|--:|--:|--:|');

  ranked.forEach((r, i) => {
    const prodRate = r.articles ? r.in_production / r.articles : 0;
    const ucRate = r.articles ? r.with_use_case / r.articles : 0;
    out.push(
      `| ${i + 1} | ${r.source_name} | ${r.articles} | ${Math.round(r.mean_ai)} `
      + `| ${r.in_production} (${Math.round(prodRate * 100)}%) `
      + `| ${r.with_use_case} (${Math.round(ucRate * 100)}%) | **${r.score}** |`);
  });

  out.push('');
  out.push('## What each source covers');
  out.push('');
  out.push('The L1 processes a source writes about most. A source concentrated on one');
  out.push('process is not worse than a broad one — it is the thing to reach for when');
  out.push('that process is the question.');
  out.push('');

  for (const r of ranked.slice(0, 20)) {
    const procs = (byProcess.get(r.source_id) ?? [])
      .sort((a, b) => b.n - a.n).slice(0, 4);
    if (procs.length === 0) continue;
    const share = procs.map((p) => `${p.value} (${p.n})`).join(', ');
    out.push(`- **${r.source_name}** — ${share}`);
  }

  out.push('');
  out.push('## Reading it');
  out.push('');
  out.push('**Mean AI focus** near the floor of 30 means a source clears the gate');
  out.push('without ever being really about AI. Volume from such a source is noise');
  out.push('that happens to be admissible.');
  out.push('');
  out.push('**In production** is the measure to optimise. It is the difference between');
  out.push('a market-intelligence tool and a clippings file. A source at 0% over a');
  out.push('meaningful number of articles publishes commentary, not deployments —');
  out.push('worth keeping only if nothing else covers its region or segment.');
  out.push('');
  out.push('**Use case described** low with production high means a source reports that');
  out.push('things launched without saying what they do. Useful for counting adoption,');
  out.push('weak for understanding it.');
  out.push('');
  out.push('## Where to look for more sources');
  out.push('');
  out.push('The pattern in the table is the guide, and so far it is consistent:');
  out.push('');
  out.push('1. **Trade press beats general press.** A wealth or banking-technology');
  out.push('   title writes about banks deploying things because that is its whole');
  out.push('   beat. A general title writes about AI, and banks appear incidentally.');
  out.push('2. **Search queries beat feed URLs.** Publications retire RSS without');
  out.push('   notice; a site-scoped search reaches them regardless and cannot 404.');
  out.push('3. **Deployment verbs beat topic words.** The query built on "rolls out",');
  out.push('   "goes live" and "deploys" yields fewer articles and better ones than');
  out.push('   the query built on "artificial intelligence".');
  out.push('4. **Regulators and consultancies are low-yield but not worthless.** They');
  out.push('   publish rarely on this topic and matter a great deal when they do.');
  out.push('   Judge them on production evidence, never on volume.');
  out.push('');

  const barren = ranked.filter((r) => r.articles >= 5 && r.in_production === 0);
  if (barren.length > 0) {
    out.push('## Candidates to drop');
    out.push('');
    out.push('Five or more articles and no evidence of production in any of them:');
    out.push('');
    for (const r of barren) {
      out.push(`- ${r.source_name} — ${r.articles} articles, mean AI focus `
             + `${Math.round(r.mean_ai)} ${bar(r.mean_ai / 100)}`);
    }
    out.push('');
  }

  return out.join('\n') + '\n';
}

export async function collect(creds: D1Credentials) {
  const rows = await queryRows<SourceRow>(creds, `
    SELECT a.source_id,
           a.source_name,
           a.publisher_kind,
           count(*)                                            AS articles,
           avg(COALESCE(sc.ai_intensity, 0))                   AS mean_ai,
           max(COALESCE(sc.ai_intensity, 0))                   AS max_ai,
           sum(CASE WHEN sc.maturity = 'in_production' THEN 1 ELSE 0 END) AS in_production,
           sum(CASE WHEN sc.maturity = 'pilot'         THEN 1 ELSE 0 END) AS piloting,
           sum(CASE WHEN sc.use_case_evidence IS NOT NULL AND sc.use_case_evidence <> ''
                    THEN 1 ELSE 0 END)                         AS with_use_case,
           min(a.published_at)                                 AS first_seen,
           max(a.published_at)                                 AS last_seen
      FROM articles a
      LEFT JOIN article_scores sc ON sc.article_id = a.id
     WHERE COALESCE(sc.relevance_score, 0) > 0
     GROUP BY a.source_id, a.source_name, a.publisher_kind
     HAVING articles > 0
     ORDER BY articles DESC;`);

  const processes = await queryRows<ProcessRow>(creds, `
    SELECT a.source_id, t.value, count(*) AS n
      FROM articles a
      JOIN article_tags t ON t.article_id = a.id AND t.dimension = 'l1_process'
      LEFT JOIN article_scores sc ON sc.article_id = a.id
     WHERE COALESCE(sc.relevance_score, 0) > 0
     GROUP BY a.source_id, t.value;`);

  return { rows, processes };
}

const OUT = 'docs/source-quality.md';

async function main(): Promise<void> {
  const creds = credentialsFromEnv();
  if (!creds) {
    const missing = ['CLOUDFLARE_ACCOUNT_ID', 'D1_DATABASE_ID', 'CLOUDFLARE_API_TOKEN']
      .filter((k) => !process.env[k]);
    console.error(`Missing credentials: ${missing.join(', ')}`);
    process.exit(1);
  }

  const { rows, processes } = await collect(creds);
  const report = renderReport(rows, processes, new Date().toISOString().slice(0, 10));

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, report);
  console.log(report);
  console.log(`\nWritten to ${OUT}`);
}

if (process.argv[1]?.endsWith('rank-sources.ts')) {
  main().catch((err: unknown) => {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
}
